name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "bug: <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **🙏 Thanks for taking the time to fill out this bug report.**
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an description of your issue
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Enter each step you took until the problem you have seen surfaced
      value: |
        1. Run '...'
        2. Navigate to '....'
        3. Do '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: |
        Run the program with `--log-level debug` and post its output here.
      render: bash
    validations:
      required: true
